---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: podinfo
    repo: https://stefanprodan.github.io/podinfo
    version: "6.7.0"
    releaseName: podinfo
    includeCRDs: true
    namespace: podinfotest
    valuesFile: ./../../../base/values.yaml
    additionalValuesFiles:
      - ./values.yaml
