---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: "37.1.0"
    releaseName: linkerd-traefik
    includeCRDs: false
    namespace: linkerd-traefik
    valuesFile: ./values.yaml
