podAnnotations:
  secret.reloader.stakater.com/reload: "linkerd-proxy-injector-k8s-tls,linkerd-identity-issuer,linkerd-sp-validator-k8s-tls,linkerd-policy-validator-k8s-tls"
  configmap.reloader.stakater.com/reload: "linkerd-config,linkerd-identity-trust-roots,linkerd-identity-trust-roots"

deploymentStrategy:
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 25%

identity:
  externalCA: true
  issuer:
    scheme: kubernetes.io/tls
    clockSkewAllowance: 60s
    issuanceLifetime: 1h0m0s

policyValidator:
  externalSecret: true
  injectCaFrom: linkerd/linkerd-policy-validator

proxyInjector:
  externalSecret: true
  injectCaFrom: linkerd/linkerd-proxy-injector

profileValidator:
  externalSecret: true
  injectCaFrom: linkerd/linkerd-sp-validator

nodeSelector:
  topology.kubernetes.io/zone: m

controllerReplicas: 3

controller:
  podDisruptionBudget:
    maxUnavailable: 1

enablePodDisruptionBudget: true

highAvailability: true

clusterDomain: cluster.local
controllerLogLevel: info
controllerLogFormat: plain
controlPlaneTracing: false
controlPlaneTracingNamespace: linkerd-jaeger
enablePodAntiAffinity: true

webhookFailurePolicy: Fail #Ignore # Fail this will preven pod scheaduling if linkerd wont patch pod with injector

prometheusUrl: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"

proxyInit:
  iptablesMode: nft
  logLevel: "info"
  # -- Default set of outbound ports to skip via iptables
  # - Galera (4567,4568)
  # k3s issue https://github.com/linkerd/linkerd2/issues/7970
  ignoreOutboundPorts: "4567,4568,6443"

# proxy configuration
proxy:
  logLevel: info
  defaultInboundPolicy: "all-unauthenticated"
  # -- Enable service profiles for non-Kubernetes services
  enableExternalProfiles: true
  # -- Default set of opaque ports
  # - SMTP (25,587) server-first
  # - MYSQL (3306) server-first
  # - Galera (4444) server-first
  # - PostgreSQL (5432) server-first
  # - Redis (6379) server-first
  # - ElasticSearch (9300) server-first
  # - Memcached (11211) clients do not issue any preamble, which breaks detection
  opaquePorts: "25,587,3306,4444,5432,6379,9300,11211"
